### ISSUE TITLE
Info regarding pretrained models

### ISSUE THREAD

**Issue by thakral-kartik** [somepago/DCR#6]
Hi,

I really liked your work!!!
Do you have plans of releasing pretrained models ?
Also, for stable diffusion experiment, does any finetuning is required as it is already trained on Laion 2B dataset ?

Thanks,
Kartik

**Comment by somepago** [comment]
Hi, since the models are quite dependent on the dataset split, we were not going to release the models. Feel free to raise an issue if you could not replicate anything in the paper.
