### ISSUE TITLE
Mitigation strategies：Training-time mitigation strategy and inference time mitigation strategy do not use the same Stable diffusion？

### ISSUE THREAD

**Issue by liuxiao-guan** [somepago/DCR#7]
Hey,

thank you for providing the code to reproduce your experiments. I want to confirm if my understanding of the different strategies using Stable diffusion versions in the 'Mitigation strategies' section of the article is correct. In the training-time mitigation strategy, you fine-tuned on Stable diffusion 2.1 and then analyzed using the generated model. However, in the inference time mitigation strategy, you directly incorporated the mitigation strategy on Stable diffusion 1.4?

**Comment by somepago** [comment]
In the paper, we used SD 2.1 for the inference time mitigation as well. 
(I guess I pushed the code version when I was testing the same for SD 1.4.)
